import type { Metadata } from "next";
import { Inter, Permanent_Marker, Red_Rose } from "next/font/google";
import "./globals.css";
import { Footer, NavBar } from "./_components";

const inter = Inter({ subsets: ["latin"] });
export const redRoseFont = Red_Rose({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
